{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-specr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/specr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/specr/specr_{{ version }}.tar.gz
  sha256: 5db5060ae27e65df84cb66d691185098ff5a91daf6c227519d1de89b530fedf8

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-broom
    - r-cowplot
    - r-dplyr
    - r-furrr
    - r-future
    - r-ggplot2
    - r-ggraph
    - r-glue
    - r-igraph
    - r-lifecycle
    - r-lme4
    - r-magrittr
    - r-parallelly
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-broom
    - r-cowplot
    - r-dplyr
    - r-furrr
    - r-future
    - r-ggplot2
    - r-ggraph
    - r-glue
    - r-igraph
    - r-lifecycle
    - r-lme4
    - r-magrittr
    - r-parallelly
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('specr')"           # [not win]
    - "\"%R%\" -e \"library('specr')\""  # [win]

about:
  home: https://masurp.github.io/specr/
  dev_url: https://github.com/masurp/specr
  license: GPL-3.0-only
  summary: 'Provides utilities for conducting specification curve analyses (Simonsohn, Simmons
    & Nelson (2020, <doi: 10.1038/s41562-020-0912-z>) or multiverse analyses (Steegen,
    Tuerlinckx, Gelman & Vanpaemel, 2016, <doi: 10.1177/1745691616658637>) including
    functions to setup, run, evaluate, and plot all specifications.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - JNuss71

# Package: specr
# Title: Conducting and Visualizing Specification Curve Analyses
# Version: 1.0.0
# Authors@R: c( person(given = "Philipp K.", family = "Masur", role = c("aut", "cre"), email = "phil.masur@gmail.com", comment = c(ORCID = "https://orcid.org/0000-0003-3065-7305")), person(given = "Michael", family = "Scharkow", role = c("aut"), email = "michael@underused.org") )
# Description: Provides utilities for conducting specification curve analyses (Simonsohn, Simmons & Nelson (2020, <doi: 10.1038/s41562-020-0912-z>) or multiverse analyses (Steegen, Tuerlinckx, Gelman & Vanpaemel, 2016, <doi: 10.1177/1745691616658637>) including functions to setup, run, evaluate, and plot all specifications.
# License: GPL-3
# URL: https://masurp.github.io/specr/, https://github.com/masurp/specr
# BugReports: https://github.com/masurp/specr/issues
# Depends: R (>= 3.5.0)
# Imports: broom, cowplot, dplyr, furrr, future, ggplot2, ggraph, glue, igraph, lifecycle, lme4, magrittr, methods, parallelly, purrr, rlang, stringr, tibble, tidyr
# Suggests: broom.mixed, gapminder, ggridges, knitr, lavaan, testthat, tidyverse, performance, rmarkdown
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2023-01-20 13:17:23 UTC; philippmasur
# Author: Philipp K. Masur [aut, cre] (<https://orcid.org/0000-0003-3065-7305>), Michael Scharkow [aut]
# Maintainer: Philipp K. Masur <phil.masur@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-01-20 13:50:02 UTC
